### ISSUE TITLE
Box account.  Overview shows that it's almost full but nothing in files? 

### ISSUE THREAD

**Issue by HPMoehnheimer** [cgollner/unclouded#85]

**Comment by cgollner** [comment]
What is wrong? 

It showing that it's almost full, or it not showing any files?

**Comment by HPMoehnheimer** [comment]
although it showed almost full in overview the file view didnt show any files. sorry for bothering you. i was setting up the whole app again now it works. i guess i cant really reproduce the problem. sorry. and thanks for the nice app. 

    Christian Göllner <notifications@github.com> schrieb am 19:29 Montag, 29.Februar 2016:
 

 What is wrong? It showing that it's almost full, or it not showing any files?—

**Comment by cgollner** [comment]
No problem!
